SilverStripe\View\SSViewer:
  theme: one-ring
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
---
Only:
  environment: dev
---
SilverStripe\Control\Email\Email:
  send_all_emails_to: me@example.com
---
Except:
  environment: dev
---
SilverStripe\Control\Email\Email:
  bcc_all_emails_to: me@example.com
