<?php

namespace Gandalf\OneRingRentals\Indexes;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\FullTextSearch\Search\Queries\SearchQuery;
use SilverStripe\FullTextSearch\Solr\SolrIndex;

class OneRingIndex extends SolrIndex
{

    protected $facets = [];

    protected $facetFilter = [];
    /**
     * Initialise the index
     */
    public function init()
    {
        $this->addClass(SiteTree::class);
        $this->addClass(\Region::class);
        $this->addClass(\Property::class);

        $this->addFilterField('ShowInSearch');

        $this->addFulltextField('Title');
        $this->addFulltextField('Description');
        $this->addFulltextField('Content');
        $this->addFulltextField('Region.Title'); // Property
        $this->addFulltextField('Regions.Title');
        $this->addFulltextField('Regions.Description');
        $this->addFilterField('Regions.ID');
        $this->addFilterField('RegionID');
    }

    public function addFacetField($field)
    {
        $this->facets[] = str_replace('.', '_', $field);
    }

    public function addFacetFilter($field, $value)
    {
        $this->facetFilter[$field] = $value;
    }

    public function search(SearchQuery $query, $offset = -1, $limit = -1, $params = array())
    {
        if (count($this->facets)) {
            $params['facet'] = 'true';
            $params['facet.field'] = $this->facets;
        }

        return parent::search($query, $offset, $limit, $params); // TODO: Change the autogenerated stub
    }
}
